appS6/src/Entity/Subscription.php
<?php

namespace App\Entity;

use App\Repository\SubscriptionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SubscriptionRepository::class)]
class Subscription
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $pdf_limit = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column(length: 255)]
    private ?string $media = null;

    /**
     * @var Collection<int, User>
     */
    #[ORM\OneToMany(targetEntity: User::class, mappedBy: 'subscription')]
    private Collection $users;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPdfLimit(): ?int
    {
        return $this->pdf_limit;
    }

    public function setPdfLimit(int $pdf_limit): static
    {
        $this->pdf_limit = $pdf_limit;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getMedia(): ?string
    {
        return $this->media;
    }

    public function setMedia(string $media): static
    {
        $this->media = $media;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->setSubscription($this);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getSubscription() === $this) {
                $user->setSubscription(null);
            }
        }

        return $this;
    }
}

appS6/src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\SubscriptionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(SubscriptionRepository $subscriptionRepository): Response
    {
        // récupérer toutes les subscriptions rangée par price
        $subscriptions = $subscriptionRepository->findBy([], ['price' => 'ASC']);

        return $this->render('home/index.html.twig', [
            'subscriptions' => $subscriptions,
        ]);
    }
}

appS6/templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}PDF Craft{% endblock %}


{% block main %}
    {% if app.user %}
        <p>Vous êtes connecté en tant que {{ app.user.email }}</p>
    {% endif %}
    <h1>pdf-craft</h1>
    <p>
        PDF Craft vous permet de générer et stocker des fichiers PDF à partir de plusieurs sources.
        <br>
        Tranformez des images, des pages web, des fichiers Word, Excel ou créez des PDF personnalisés en quelques clics
        et stockez-les dans votre espace personnel.
    </p>

    <section class="row m-auto d-flex flex-wrap justify-content-center gap-5 mt-5">
        <h2>Nos offres</h2>
        {% for subscription in subscriptions %}
            <div class="my_card my_card_presentation col-lg-3 col-12 p-0 flex-grow-1
            {% if app.user and app.user.subscription == subscription %}
            active
            {% endif %}
            ">
                <div class="card-content d-flex flex-column justify-content-between h-100">
                    <div class="card-banner d-flex flex-column align-items-center p-4">
                        <div class="d-flex">
                            {% set starCount = loop.index %}
                            {% for i in 1..starCount %}
                                <twig:ux:icon name="bi:star-fill" height="16" width="16"/>
                            {% endfor %}
                        </div>
                        <h3>{{ subscription.title }}</h3>
                        <h4 class="text-center">{{ subscription.price }} €/mois</h4>
                    </div>
                    <div class="card-body">
                        <h5 class="text-center">{{ subscription.pdfLimit }} PDFs/jour</h5>
                        <hr>
                        <p>{{ subscription.description }}</p>
                    </div>
                    <div class="card-footer d-flex justify-content-center mb-4">
                        {% if app.user and app.user.subscription == subscription %}
                            <button class="btn btn-primary-color disabled">Actif</button>
                        {% else %}
                            <a href="{{ path('app_subscribe', {'id': subscription.id}) }}">
                                <button class="btn
                            {% set starCount = loop.index %}
                            {% if loop.index == 2 %}
                            btn-primary-color
                            {% else %}
                            btn-primary-color-outline
                            {% endif %}
                            ">Souscrire
                                </button>
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </section>

{% endblock %}